### ISSUE TITLE
Can't be built: `add_library cannot create target "Valor" because another target with the same name already exists`

### ISSUE THREAD

**Issue by Akira13641** [D7ry/Valor#1]
It would seem that your local setup for this repo (and also Valhalla, which has the same issue currently) must be slightly different in terms of the CMake files, as what you get when checking out the repos as-is does not seem to be considered valid by any recent version of CMake itself.

**Comment by D7ry** [comment]
Have you managed to resolve this issue? I'm able to build through this repo's cmake setup and clib-NG in my `path` on any windows OS. It'd be helpful if you could provide a build log so I can look into that. Thanks
